# Generated by Django 4.2.7 on 2023-12-13 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='username', max_length=200, unique=True, verbose_name='Username')),
                ('firstname', models.CharField(default='firstname', max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(default='lastname', max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(default='email', max_length=200, unique=True, verbose_name='Email')),
                ('password', models.CharField(default='password', help_text='Be Careful on changing passwords directly from the admin site, make sure to input the plain text password! Do not save if will the password not being in plain text or else it will be set to the current value(encrypted) and not as intended', max_length=200, verbose_name='Password')),
                ('type', models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20, verbose_name='Account Type')),
                ('image', models.ImageField(default='media/thumbnails/user-default.png', upload_to='thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Exam Title', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='{% static "main/assets/badges" %}')),
                ('name', models.CharField(max_length=255)),
                ('requirements', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Learn1',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID')),
                ('unitNo', models.IntegerField(default=0, verbose_name='Unit No')),
                ('lessonNo', models.IntegerField(default=1, verbose_name='Lesson No.')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField(default='The content of the lesson should go here.')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 12, 13, 17, 6, 19, 290724), verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='No Quiz Title', max_length=255)),
                ('lesson', models.CharField(default='Lesson', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_no', models.IntegerField(primary_key=True, serialize=False, unique=True, verbose_name='Student No.')),
                ('firstname', models.CharField(default='firstname', max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(default='lastname', max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(default='email', max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField(default=1, verbose_name='Unit No.')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Quiz_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('optionA', models.CharField(default='A', max_length=255)),
                ('optionB', models.CharField(default='B', max_length=255)),
                ('optionC', models.CharField(default='C', max_length=255)),
                ('optionD', models.CharField(default='D', max_length=255)),
                ('correct_choice', models.CharField(max_length=1)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quiz')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title here', max_length=200, verbose_name='Title')),
                ('content', models.TextField(default='The content of the lesson should go here.', verbose_name='Content')),
                ('published', models.DateTimeField(default=datetime.datetime(2023, 12, 13, 17, 6, 19, 291714), verbose_name='date published')),
                ('unit_no', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Assessment_Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField()),
                ('choices', models.JSONField()),
                ('correct_choice', models.CharField(max_length=1)),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.assessment')),
            ],
        ),
        migrations.AddField(
            model_name='assessment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learn1'),
        ),
    ]
