# Generated by Django 4.2.7 on 2023-12-13 17:52

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assessment_question',
            name='choices',
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='optionA',
            field=models.CharField(default='A', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='optionB',
            field=models.CharField(default='B', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='optionC',
            field=models.CharField(default='C', max_length=255),
        ),
        migrations.AddField(
            model_name='assessment_question',
            name='optionD',
            field=models.CharField(default='D', max_length=255),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 1, 52, 25, 953235), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 1, 52, 25, 953235), verbose_name='date published'),
        ),
        migrations.CreateModel(
            name='UserBadge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.badge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.student')),
            ],
        ),
    ]
