# Generated by Django 4.2.7 on 2023-11-18 16:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 19, 0, 13, 18, 542029), verbose_name='date published'),
        ),
    ]
