# Generated by Django 4.2.7 on 2023-12-13 19:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_assessment_question_choices_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lesson',
            field=models.CharField(default='Lesson', max_length=255),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 56, 53, 227919), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 3, 56, 53, 227919), verbose_name='date published'),
        ),
    ]
