# Generated by Django 4.2.7 on 2023-11-19 16:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_learn1_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 20, 0, 14, 48, 730899), verbose_name='date published'),
        ),
    ]
