# Generated by Django 4.2.7 on 2023-11-24 10:58

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_learn1_published'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_no', models.IntegerField(verbose_name='Student No.')),
                ('firstname', models.CharField(default='firstname', max_length=200, verbose_name='First Name')),
                ('lastname', models.CharField(default='lastname', max_length=200, verbose_name='Last Name')),
                ('email', models.CharField(default='email', max_length=200, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_no', models.IntegerField(default=1, verbose_name='Unit No.')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='content',
            field=models.TextField(default='The content of the lesson should go here.', verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 58, 47, 426638), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='Title here', max_length=200, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='content',
            field=models.TextField(default='The content of the lesson should go here.'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 18, 58, 47, 426638), verbose_name='date published'),
        ),
        migrations.AddField(
            model_name='lesson',
            name='unit_no',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main.unit'),
        ),
    ]
