# Generated by Django 4.2.7 on 2023-11-24 11:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_student_unit_lesson_content_lesson_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 19, 5, 28, 737341), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 24, 19, 5, 28, 737341), verbose_name='date published'),
        ),
    ]
