# Generated by Django 4.2.7 on 2023-11-26 18:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_student_id_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 2, 34, 54, 561443), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 27, 2, 34, 54, 561443), verbose_name='date published'),
        ),
    ]

# Generated by Django 4.2.7 on 2023-11-26 13:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_student_id_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 21, 40, 29, 233815), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 26, 21, 40, 29, 233815), verbose_name='date published'),
        ),
    ]
