# Generated by Django 4.2.7 on 2023-12-02 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_unit_alter_learn1_published'),
        ('main', '0009_alter_learn1_published_alter_lesson_published'),
    ]

    operations = [
    ]
