# Generated by Django 4.2.7 on 2023-12-13 05:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_quiz_question_optiona_quiz_question_optionb_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lesson',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 30, 18, 829806), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 30, 18, 829806), verbose_name='date published'),
        ),
    ]
