# Generated by Django 4.2.7 on 2023-12-13 05:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_assessment_lesson_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.learn1'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 36, 56, 988181), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 36, 56, 989181), verbose_name='date published'),
        ),
    ]
