# Generated by Django 4.2.7 on 2023-12-13 05:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_assessment_lesson_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 37, 41, 522864), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 13, 13, 37, 41, 523863), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.CharField(max_length=255),
        ),
    ]
