# Generated by Django 4.2.7 on 2023-12-03 00:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_account_image_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(default='main/assets/thumbnails/user-default.png', upload_to='{% static "main/assets/thumbnails" %}'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 8, 30, 49, 502037), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 8, 30, 49, 502037), verbose_name='date published'),
        ),
    ]
