# Generated by Django 4.2.7 on 2023-12-03 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_alter_account_image_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], default='Student', max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 8, 37, 16, 597621), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 8, 37, 16, 597621), verbose_name='date published'),
        ),
    ]
