# Generated by Django 4.2.7 on 2023-12-03 02:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_learn1_published_alter_lesson_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='image',
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 10, 11, 7, 693844), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 3, 10, 11, 7, 693844), verbose_name='date published'),
        ),
    ]
