# Generated by Django 4.2.7 on 2023-12-04 15:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_account_image_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 23, 8, 32, 836996), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 4, 23, 8, 32, 836996), verbose_name='date published'),
        ),
    ]
