# Generated by Django 4.2.7 on 2023-12-04 22:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_alter_account_type_alter_learn1_published_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='type',
            field=models.CharField(choices=[('Student', 'Student'), ('Teacher', 'Teacher')], max_length=20, verbose_name='Account Type'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 6, 17, 5, 743116), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 5, 6, 17, 5, 744123), verbose_name='date published'),
        ),
    ]
