# Generated by Django 4.2.7 on 2023-12-06 01:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_alter_account_password_alter_learn1_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='learn1',
            name='lessonNo',
            field=models.IntegerField(default=0, verbose_name='Lesson No.'),
        ),
        migrations.AddField(
            model_name='learn1',
            name='unitNo',
            field=models.IntegerField(default=0, verbose_name='Unit No'),
        ),
        migrations.AlterField(
            model_name='learn1',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 51, 13, 504865), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='published',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 9, 51, 13, 504865), verbose_name='date published'),
        ),
    ]
